version: "3"

networks:
  elevated:
  nginx_nginx-network:
    external: true

services:
  service:
    image: ghcr.io/bnorm/elevated-service:latest
    restart: unless-stopped
    networks:
      - elevated
      - nginx_nginx-network
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test
      SPRING_PROFILES_ACTIVE: cloud
      JWT_SECRET: ${JWT_SECRET}

  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    networks:
      - elevated
    ports:
      - "27017:27017"

volumes:
  certbot-etc:
  certbot-var:
