version: "3"

services:
  raspberry:
    image: ghcr.io/bnorm/elevated-iot-raspberry:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    privileged: true
    environment:
      - "DEVICE_KEY=${DEVICE_KEY}"
