
### User login

POST {{hostname}}/api/v1/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

> {% client.global.set("authorization", response.body.token.type + " " + response.body.token.value); %}

### Get all charts

GET {{hostname}}/api/v1/charts
Authorization: {{authorization}}
Accept: application/json

### Get chart

GET {{hostname}}/api/v1/charts/{{chartId}}
Authorization: {{authorization}}
Accept: application/json

> {% client.global.set("chartId", response.body.id); %}

### Patch chart

PATCH {{hostname}}/api/v1/charts/{{chartId}}
Authorization: {{authorization}}
Accept: application/json
Content-Type: application/json

{
    "name": "Active Chart",
    "bounds": [
        {
            "type": "PH",
            "low": 5.7,
            "high": 6.3
        },
        {
            "type": "EC",
            "low": 550,
            "high": 750
        }
    ],
    "amounts": {
        "GENERAL_HYDROPONICS_PH_DOWN": 1.0,
        "GENERAL_HYDROPONICS_MICRO": 4.9,
        "GENERAL_HYDROPONICS_GRO": 4.6,
        "GENERAL_HYDROPONICS_BLOOM": 3.4
    }
}

#### Create chart
## "Grow Week 1", 500, 600, 2.0, 2.0, 2.0
## "Grow Week 2", 1000, 1200, 4.2, 3.8, 3.0
## "Grow Week 3", 1300, 1600, 5.6, 5.2, 3.8
## "Grow Week 4", 1600, 2000, 6.8, 6.4, 4.8
## "Bloom Week 1", 1600, 1900, 6.1, 5.3, 6.8
## "Bloom Week 2", 1600, 1900, 6.1, 5.3, 6.8
## "Bloom Week 3", 1600, 1900, 5.3, 5.3, 7.6
## "Bloom Week 4", 1600, 1900, 5.3, 5.3, 7.6
## "Bloom Week 5", 1600, 1900, 5.3, 5.3, 7.6
## "Bloom Week 6", 1000, 1300, 3.8, 3.8, 4.5
## "Bloom Week 7", 1000, 1300, 3.8, 3.8, 4.6
## "Bloom Week 8", 700, 900, 2.3, 2.3, 3.6
#
#POST {{hostname}}/api/v1/charts
#Authorization: {{authorization}}
#Accept: application/json
#Content-Type: application/json
#
#{
#    "name": "Grow Week 1",
#    "bounds": [
#        {
#            "type": "PH",
#            "low": 5.7,
#            "high": 6.3
#        },
#        {
#            "type": "EC",
#            "low": 500,
#            "high": 600
#        }
#    ],
#    "amounts": {
#        "GENERAL_HYDROPONICS_PH_DOWN": 1.0,
#        "GENERAL_HYDROPONICS_MICRO": 2.0,
#        "GENERAL_HYDROPONICS_GRO": 2.0,
#        "GENERAL_HYDROPONICS_BLOOM": 2.0
#    }
#}
#
#> {% client.global.set("chartId", response.body.id); %}

#### Delete chart
#
#DELETE {{hostname}}/api/v1/charts/{{chartId}}
#Authorization: {{authorization}}
#Accept: application/json
#
#> {% client.global.clear("chartId"); %}
