
### User login

POST {{hostname}}/api/v1/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("authorization", response.body.token.type + " " + response.body.token.value); %}

### Get all devices

GET {{hostname}}/api/v1/devices
Authorization: {{authorization}}
Accept: application/json

### Get device

GET {{hostname}}/api/v1/devices/{{deviceId}}
Authorization: {{authorization}}
Accept: application/json

> {% client.global.set("deviceId", response.body.id); %}

### Patch device

PATCH {{hostname}}/api/v1/devices/{{deviceId}}
Authorization: {{authorization}}
Accept: application/json
Content-Type: application/json

{
}

### Get device actions

GET {{hostname}}/api/v1/devices/{{deviceId}}/actions?submittedAfter=2000-01-01T00:00:00.000Z
Authorization: {{authorization}}
Accept: application/json

### Submit device action

POST {{hostname}}/api/v1/devices/{{deviceId}}/actions
Authorization: {{authorization}}
Accept: application/json
Content-Type: application/json

{
  "args": {
    "type": "PUMP_DISPENSE",
    "pump": 5,
    "amount": 1
  }
}

> {% client.global.set("actionId", response.body.id); %}

### Get device action

GET {{hostname}}/api/v1/devices/{{deviceId}}/actions/{{actionId}}
Authorization: {{authorization}}
Accept: application/json

> {% client.global.set("actionId", response.body.id); %}

### Delete device action

DELETE {{hostname}}/api/v1/devices/{{deviceId}}/actions/{{actionId}}
Authorization: {{authorization}}
Accept: application/json

> {% client.global.clear("actionId"); %}

### Device login

POST {{hostname}}/api/v1/devices/login
Authorization: {{authorization}}
Accept: application/json
Content-Type: application/json

{
  "id": "{{deviceId}}",
  "key": "{{deviceKey}}"
}

> {% client.global.set("authorization", response.body.token.type + " " + response.body.token.value); %}

#### Create device
#
#POST {{hostname}}/api/v1/devices
#Authorization: {{authorization}}
#Accept: application/json
#Content-Type: application/json
#
#{
#  "name": "Sample Device",
#  "key": "{{deviceKey}}"
#}
#
#> {% client.global.set("deviceId", response.body.id); %}

#### Delete device
#
#DELETE {{hostname}}/api/v1/devices/{{deviceId}}
#Authorization: {{authorization}}
#Accept: application/json
#
#> {% client.global.clear("deviceId"); %}
