name: Project Build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:

  # TODO add JUnit report to PRs and artifacts
  gradle-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew check bootJar

      - uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build elevated-service
      # TODO can this be put in a matrix? https://github.com/docker/build-push-action/issues/561
      - uses: docker/metadata-action@v3
        id: meta-service
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}
        with:
          images: |
            ghcr.io/bnorm/elevated-service
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}
        with:
          context: ./service
          push: true
          tags: ${{ steps.meta-service.outputs.tags }}
          labels: ${{ steps.meta-service.outputs.labels }}

      # Build elevated-raspberry
      # TODO can this be put in a matrix? https://github.com/docker/build-push-action/issues/561
      - uses: docker/metadata-action@v3
        id: meta-iot-raspberry
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}
        with:
          images: |
            ghcr.io/bnorm/elevated-iot-raspberry
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}
        with:
          context: ./iot/raspberry
          push: true
          tags: ${{ steps.meta-iot-raspberry.outputs.tags }}
          labels: ${{ steps.meta-iot-raspberry.outputs.labels }}

  application-deploy:
    runs-on: ubuntu-latest
    needs: gradle-build
    if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Copy deployment configuration files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          strip_components: 1
          source: "deploy/"
          target: "~/"

      - name: Deploy latest version of service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd elevated
            docker compose pull service
            docker compose up -d
            docker compose exec -it nginx nginx -s reload
            docker image prune -f

#      - uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
