name: Project Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:

  # TODO add JUnit report to PRs and artifacts
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
