name: Application Deployment

on:
  push:
    tags:
      - '*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:

  service-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Build project
      # TODO could this be a separate job which shares results with image builds?
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew bootJar

      # Build elevated-service
      # TODO if there are multiple services, can this be put in a matrix? https://github.com/docker/build-push-action/issues/561
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/bnorm/elevated-service
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  application-deploy:
    runs-on: ubuntu-latest
    needs: service-build

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Copy deployment configuration files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          strip_components: 1
          source: "deploy/"
          target: "~/"

      - name: Deploy latest version of service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd elevated
            docker compose pull service
            docker compose up -d
            docker compose exec -it nginx nginx -s reload
            docker image prune -f

#      - uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
