name: Let's Encrypt

on:
  schedule:
    - cron: '0 5 * * *'

jobs:

  cert-update:
    name: "Certificate Update"
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/elevated' }}

    steps:
      - name: Deploy latest version of service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd elevated
            docker compose up -d certbot
            docker compose exec -it nginx nginx -s reload
